### ISSUE TITLE
Save BufferedImage/Bitmap as a TGA file

### ISSUE THREAD

**Issue by ChrisMCMine** [npedotnet/TGAReader#1]
It would be convenient to have built-in methods to save a BufferedImage or a Bitmap as a TGA file

**Comment by npedotnet** [comment]
Please try TGAWriter. :smile: 
https://github.com/npedotnet/TGAReader/blob/master/README.md#tgawriter

**Comment by ChrisMCMine** [comment]
Great, thanks!
